# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: config/samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: config/units.tsv

# optional inclusion of certain rules -------------------------------------------------------
mergeReads:
  activate: False

# text file containing list of chromosomes to keep when filtering ---------------------------
filter_chroms: True
keep_chroms: config/keep_chroms.txt

# reference genome options ------------------------------------------------------------------
ref_genome:
  name: dm6
  link: https://hgdownload.soe.ucsc.edu/goldenPath/dm6/bigZips/dm6.fa.gz

ref_annotation:
  name: flybase_dm6
  link: http://ftp.flybase.net/releases/current/dmel_r6.45/gff/dmel-all-r6.45.gff.gz

# spike-in genome options ------------------------------------------------------------------
use_spikeIn: False

spikeIn_genome:
  name: yeast_w303
  link: http://sgd-archive.yeastgenome.org/sequence/strains/W303/W303_SGD_2015_JRIU00000000/W303_SGD_2015_JRIU00000000.fsa.gz


# DESeq2 options -------------------------------------------------------------------------
diff_exp:
  # contrasts for the deseq2 results method
  contrasts:
    degrad-vs-control:
      - degrad
      - control
  model: ~condition
  count_threshold: 50

# changes to rule paramters ---------------------------------------------------------------
params:
  hisat2_index: ""
  hisat2_align: "-k 2 --very-sensitive --no-mixed --no-discordant"
  filter_multireads: "-f bam -F '(mapping_quality >= 30) and ([XS] == null)'" 
  bigwigs_ind: "--binSize 10"
  bigwigs_merged: "--binSize 10"